CREATE DATABASE FOOD
GO
USE FOOD
GO
-- TẠO BẢNG DANH SÁCH NGƯỜI DÙNG
CREATE TABLE ACCOUNT
(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(40),
EMAIL VARCHAR(80),
PASSWORDHASH VARCHAR(100),
SALT VARCHAR (100),
BIRTHDATE DATETIME,
GENDER NVARCHAR(5)
)
--TẠO RÀNG BUỘC CHO BẢNG USER
ALTER TABLE ACCOUNT
ADD CONSTRAINT C_GENDER
CHECK ( GENDER IN('NAM',N'NỮ'))
-- TẠO BẢNG DANH SÁCH ROLE CHO USER
CREATE TABLE ACCOUNT_ROLE
(
ID INT IDENTITY(1,1) PRIMARY KEY,
IDROLE INT,
IDUSER INT
)
-- TẠO BẢNG DANH SÁCH CÁC ROLE
CREATE TABLE LIST_ROLE
(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR (20)
)
--THÊM BẢNG ĐĂNG NHẬP VỚI FACEBOKK,GOOGLE,...
CREATE TABLE EXTERNALACCOUNT
(
IDUSER INT IDENTITY(1,1) ,
LOGINPROVIDER char (20),
PROVIDERKEY NVARCHAR(100) NOT NULL
)
--THÊM KHÓA CHÍNH CHO BẢNG EXTERNALACCOUNT
ALTER TABLE EXTERNALACCOUNT
ADD CONSTRAINT PK_EXTERNALACCOUNT
PRIMARY KEY(IDUSER,PROVIDERKEY) 

--THÊM BẢNG MÓN ĂN
CREATE TABLE FOOD
(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR (30),
DECRIPTION NVARCHAR(100),
RATING INT,
IDTYPE INT,
STATUSFOOD INT,
IMGFOOD NVARCHAR(100),
PRICE FLOAT,
DATESALE DATETIME,
)
--TẠO RÀNG BUỘC CHO BẢNG FOOD
ALTER TABLE FOOD
ADD CONSTRAINT C_FOOD
CHECK ( STATUSFOOD IN(1,0))
--THÊM BẢNG LOẠI THỨC ĂN
CREATE TABLE TYPEFOOD
(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR (20),
TIMESTART TIME,
TIMEEND TIME
)
-- THÊM KHÓA NGOẠI CHO BẢNG ACCOUNT_ROLE VÀ ACCOUNT
ALTER TABLE ACCOUNT_ROLE
ADD CONSTRAINT FK_ACCOUNT_ROLE_ACCOUNT
FOREIGN KEY (IDUSER)
REFERENCES ACCOUNT(ID)
--THÊM KHÓA NGOẠI CHO BẢNG ACCOUNT_ROLE VÀ LIST_ROLE
ALTER TABLE ACCOUNT_ROLE
ADD CONSTRAINT FK_ACCOUNT_ROLE_LIST_ROLE
FOREIGN KEY (IDROLE)
REFERENCES LIST_ROLE(ID)
--THÊM KHÓA NGOẠI CHO BẢNG FOOD VÀ TYPE_FOOD
ALTER TABLE FOOD
ADD CONSTRAINT FK_FOOD_TYPEFOOD
FOREIGN KEY(IDTYPE)
REFERENCES TYPEFOOD(ID)
--THÊM DỮ LIỆU BẢNG ACCOUNT
INSERT INTO LIST_ROLE(NAME) VALUES ('ADMIN')
INSERT INTO LIST_ROLE(NAME) VALUES ('CUSTOMER')
-- THÊM DỮ LIỆU BẢNG TYPE_FOOD
INSERT INTO TYPEFOOD(NAME,TIMESTART,TIMEEND) VALUES (N'ĐIỂM TÂM','06:00','9:00')
INSERT INTO TYPEFOOD(NAME,TIMESTART,TIMEEND) VALUES (N'CƠM TRƯA','10:00','13:00')
INSERT INTO TYPEFOOD(NAME,TIMESTART,TIMEEND) VALUES (N'CƠM TỐI','16:00','21:00')
--THÊM DỮ LIỆU BẢNG FOOD
INSERT INTO FOOD(NAME,DECRIPTION,RATING,IDTYPE,PRICE,DATESALE,STATUSFOOD) VALUES ('BÚN BÒ HUẾ','NGON',4,1,30000,'06/11/2016',1)
