//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORDHASH { get; set; }
        public string SALT { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string IMAGEACC { get; set; }
        public string GENDER { get; set; }
    }
}
