//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOODORDER
    {
        public int ID { get; set; }
        public int IDUSER { get; set; }
        public int IDFOOD { get; set; }
        public Nullable<int> STATUSODER { get; set; }
        public Nullable<int> NUMBER { get; set; }
    }
}
