//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPEFOOD
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.TimeSpan> TIMESTART { get; set; }
        public Nullable<System.TimeSpan> TIMEEND { get; set; }
    }
}
